# Generated by Django 5.2.18 on 2026-10-07 07:04

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires', models.DateTimeField()),
                ('tries', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('session', models.CharField(default='2026-27', max_length=20)),
                ('fields', models.JSONField(default=core.models.default_fields)),
                ('pp', models.JSONField(default=core.models.default_pp)),
                ('tpl', models.JSONField(blank=True, default=dict)),
                ('bg', models.ImageField(blank=True, null=True, upload_to=core.models.template_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('team', 'Team member'), ('school', 'School')], max_length=10)),
                ('schools', models.ManyToManyField(blank=True, related_name='members', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.photo_path)),
                ('fphoto', models.ImageField(blank=True, null=True, upload_to=core.models.photo_path)),
                ('mphoto', models.ImageField(blank=True, null=True, upload_to=core.models.photo_path)),
                ('pending', models.JSONField(blank=True, default=dict)),
                ('n_photo', models.ImageField(blank=True, null=True, upload_to=core.models.photo_path)),
                ('n_fphoto', models.ImageField(blank=True, null=True, upload_to=core.models.photo_path)),
                ('n_mphoto', models.ImageField(blank=True, null=True, upload_to=core.models.photo_path)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('appr_at', models.DateField(blank=True, null=True)),
                ('printed_at', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateField(blank=True, null=True)),
                ('chg', models.TextField(blank=True)),
                ('token', models.CharField(default=core.models.new_token, max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school')),
            ],
            options={
                'ordering': ['adm'],
                'unique_together': {('school', 'adm')},
            },
        ),
    ]
